### ISSUE TITLE
having generates unneeded and condition

### ISSUE THREAD

**Issue by Igor-Palaguta** [MihaelIsaev/SwifQL#11]
Looks like `.having(some_condition)` generates `HAVING some_condition AND some_condition` `

**Comment by MihaelIsaev** [comment]
Hmm... tried to reproduce but looks like it works as expected. Also checked tests and as tests cover `.having` and they pass then it looks like everything is ok.... let me know if I'm wrong

**Comment by MihaelIsaev** [comment]
I've just tried to do simple test in one of my apps
```swift
let query = SwifQL.having(\Club.name == "hello")
print(query.prepare(.psql).plain)
```
it prints
```sql
HAVING "Club"."name" = 'hello'
```

**Comment by Igor-Palaguta** [comment]
Probably just in `SwifQLSelectBuilder`

**Comment by Igor-Palaguta** [comment]
in wheres:
```
            if $0.offset == 0 {
                query = query.where($0.element)
            } else {
                query = query && $0.element
            }
```
but in havings without else:
```
            if $0.offset == 0 {
                query = query.having($0.element)
            }
            query = query && $0.element
```
