### ISSUE TITLE
Cannot join and decode Date field

### ISSUE THREAD

**Issue by davuthdv** [MihaelIsaev/SwifQL#13]
I have models that looks something like this
```
struct Item: Model {
    var id: UUID?
    var name: String
    var imageId: UUID?
}

struct Image: Model {
    var id: UUID?
    var url: String
    var createdAt: Date?
}
```

I create a query that does a `LEFT JOIN` from `Item` to `Image` and try to decode result into this struct:
```
struct ItemFull: Decodable {
    var id: UUID?
    var name: String
    var image: Image?
}
```
... and I got back an error `The data couldn’t be read because it isn’t in the correct format.`

So I create a new struct similar to `Image` but without the `Date` field:
```
struct ImageWithoutDate: Decodable {
    var id: UUID?
    var url: String
}
```
... and replace `var image: Image?` to `var image: ImageWithoutDate?`, it works fine. It seems that there's an issue while trying to decode the date field. Or am I missing something like date formatter somewhere?

**Comment by MihaelIsaev** [comment]
SwifQL doesn't decode anything, it just builds a raw query for you to execute it via your favourite driver. 

What driver are you using for executing a query?
Are you using Vapor? Vapor's PostgreSQL and MySQL drivers can decode dates and probably support some custom dateformatters.

In my projects I use SwiftQL with Vapor's PostgreSQL driver and have no problem with dates.
All the models are created with Vapor's Fluent migrations and dates stored in the database as `timestamp without time zone` and looks like this `2019-08-06 09:21:38.845306` so when I'm decoding my queries using `.all(decoding:)` or `.first(decoding:)` everything is ok cause dates in that very format which driver expects. If e.g. dates in your database are in different format you could cast them to needed format in your queries.

**Comment by davuthdv** [comment]
Yep. I'm doing the exact same thing. Just to clarify. If i do the query on `Image` model and decode it, it's completely fine. The problem is when I do the join query. Something like this.
```
.select(|SwifQL.select(Fn.to_jsonb(Image.table))| => "image")
```
and try to decode to `ItemFull` (not `Item`). The query works just fine. I can see my result if I just run `.all()` instead of `.all(decoding:)`. To think about it now, it seems to be more an issue with swift decoding rather than `SwifQL`. Hmm...

**Comment by MihaelIsaev** [comment]
I think you could try to build JSON object using `jsonb_build_object` to be able to cast date field to the right format

**Comment by davuthdv** [comment]
Would you mind giving me some examples how to do that?

**Comment by MihaelIsaev** [comment]
@davuthdv have you found solution? 🙂

**Comment by davuthdv** [comment]
Well, yes and no. I don't know how to use `jsonb_build_object`, and even if it works, it seems to be a bit complex. I can solve it if I decode my date field to string instead. It works, but it is a bit tedious because I need to create an almost identical model for every model I need to do the join with. What's strange about this is that decoding to date works just fine if i query that table directly. It seems that the result is different between querying directly vs joining and convert to jsonb.

**Comment by MihaelIsaev** [comment]
Could you show the full query?

I've just checked it in my project like this
```swift
struct Result: Codable {
    let createdAt: Date
    struct SubResult: Codable {
        let createdAt: Date
    }
    let organization: [SubResult]
}
let _: Future<Void> = app.requestPooledConnection(to: .psql).flatMap { conn in
    SwifQL
        .select(\JobPost.createdAt, |SwifQL.select(Fn.to_jsonb(Organization.table))| => "organization")
        .from(JobPost.table)
        .join(.left, Organization.table, on: \Organization.id == \JobPost.orgId)
        .execute(on: conn)
        .all(decoding: Result.self)
        .map {
            print("found \($0.count)")
    }
}
```

and it decodes without any problems. `createdAt` stored as `timestamp without time zone` in all my tables. In what format do you store your dates?

**Comment by davuthdv** [comment]
Ok... I have my model like this
```swift
struct FoodCategory: PostgreSQLUUIDModel {
    var id: UUID?
    var sortOrder: Int
    var enabled: Bool = true
    var imageId: FileRef.ID?
}

struct FileRef: PostgreSQLUUIDModel {
    static let createdAtKey: TimestampKey? = \.createdAt
    static let updatedAtKey: TimestampKey? = \.updatedAt
    
    var id: UUID?
    var name: String
    var type: String
    var group: FileRefGroup?
    var createdAt: Date?
    var updatedAt: Date?
}

struct Full: Codable {
    var id: UUID
    var sortOrder: Int
    var enabled: Bool
    var imageRef: FileRef?
}
```

Here's my query:

```swift
let result = try SwifQLSelectBuilder()
    .select(FoodCategory.table.*)
    .select(|SwifQL.select(Fn.to_jsonb(FileRef.table))| => "imageRef")
    .from(FoodCategory.table)
    .join(.inner, FileRef.table, on: \FileRef.id == \FoodCategory.imageId)
    .build()
    .execute(on: conn)
    .all(decoding: Full.self)
    .wait()
```

This is the plain query that it produces:
```sql
SELECT "FoodCategory".* , (SELECT to_jsonb("FileRef")) as "imageRef" FROM "FoodCategory" INNER JOIN "FileRef" ON "FileRef"."id" = "FoodCategory"."imageId"
```

if I do  `.all()` instead of `.all(decoding: Full.self)`, the query works just fine and returns this:
```
[[16449.sortOrder: 8 (BIGINT), 16449.id: 12CDFC90-066C-4CB0-B1CE-8B0214592222 (UUID), 16449.enabled: 0x01 (BOOLEAN), 16449.imageId: 36B7BB4E-2776-42BB-9C5C-F1F747D5682D (UUID), imageRef: {"id": "36b7bb4e-2776-42bb-9c5c-f1f747d5682d", "name": "73F812AD-3CEE-4164-82BC-47AC7E73EEAF.jpg", "type": "image/jpeg", "group": "food-category", "createdAt": "2019-12-05T11:55:32.855979", "updatedAt": "2019-12-05T11:55:32.86949"} (JSONB)]]
```

I create `FileRef` table with Vapor migration. And checking the database directly, the field type of `createdAt` and `updatedAt` is really "timestamp without time zone"

**Comment by MihaelIsaev** [comment]
That's really weird cause I'm getting exactly the same and it decodes

this is my raw query result
`[49915.createdAt: 0x000239dc38ba9b21 (TIMESTAMP), organization: {"id": "34e2a892-c2a9-41b2-8358-b30f4ff73803", "city": "New York", "name": "Molly", "createdAt": "2018-11-05T20:42:25.473594"} (JSONB)]`

Are you on the latest version of all Vapor's packages?
I'm on Vapor's PostgreSQL 1.5.0
PostgreSQL database v11

**Comment by davuthdv** [comment]
> Are you on the latest version of all Vapor's packages?
I'm on Vapor's PostgreSQL 1.5.0 - it decodes that data

Yes! I've just run `swift package update` again just to make sure.

> PostgreSQL database v11

I'm running on Postgres version 11.4... It's a little bit out of date, yes.

I'm just curious though. Shouldn't the `organization` a `SubResult` instead of `[SubResult]`? And does it still work if you set `createdAt` of `SubResult` to be optional `Date?`?

**Comment by MihaelIsaev** [comment]
I think it shouldn't because subselect returns an array, if you need an object instead of array then `Fn.to_jsonb` should be called without `select` like this
```swift
.select(\JobPost.createdAt, Fn.to_jsonb(Organization.table) => "organization")
```

**Comment by davuthdv** [comment]
Is it too late for me to admit that I'm so new to SQL? 😅
It's weird. Even the result that you show has the organization as an object, not an array. But I'm really not familiar with all these things. Could you try setting `Date` of `SubResult` as optional?

**Comment by MihaelIsaev** [comment]
I was wrong about `let organization: [SubResult]` it execute and decode query without errors but `organization ` is empty. If I change it to `let organization: SubResult` then it shows me an error `Value of type 'Double' required for key 'createdAt'` doesn't matter if `createdAt` optional or not.

**Comment by MihaelIsaev** [comment]
```swift
.select(\JobPost.createdAt, Fn.to_jsonb(Organization.table) => "organization")
```
and 
```swift
.select(\JobPost.createdAt, |SwifQL.select(Fn.to_jsonb(Organization.table))| => "organization")
```
is the same in the result, so I was wrong as well by saying that `select` returns an array

**Comment by MihaelIsaev** [comment]
So I'm newbie in SQL as well 😁

**Comment by davuthdv** [comment]
Haha... well, now at least we both got similar error. It's similar because I don't get that same error. I get `The data couldn’t be read because it isn’t in the correct format.`
