### ISSUE TITLE
Issue with CNIOAtomics

### ISSUE THREAD

**Issue by m-maillot** [MihaelIsaev/SwifQL#2]
I have an error when I add the SwifQL package to my project:

`Missing required module 'CNIOAtomics'`

I use Vapor 3.1.1 and SwifQL 0.9.3 but I have the same issue with the version 0.8.1.

FYI, the FluentQuery library works perfectly (0.4.31)

**Comment by MihaelIsaev** [comment]
Hello @m-maillot 

I've just tried to clone Vapor's API template, install latest SwifQL, compile&run it and it works.

Could you try to repeat my steps:
```bash
git clone https://github.com/vapor/api-template/ test
cd test
nano Package.swift
```
make `Package.swift` look like this
```swift
// swift-tools-version:4.0
import PackageDescription

let package = Package(
    name: "VaporApp",
    products: [
        .library(name: "VaporApp", targets: ["App"]),
    ],
    dependencies: [
        // 💧 A server-side Swift web framework.
        .package(url: "https://github.com/vapor/vapor.git", from: "3.0.0"),

        // 🔵 Swift ORM (queries, models, relations, etc) built on SQLite 3.
        .package(url: "https://github.com/vapor/fluent-sqlite.git", from: "3.0.0"),
        .package(url: "https://github.com/MihaelIsaev/SwifQL.git", from:"0.9.3")
    ],
    targets: [
        .target(name: "App", dependencies: ["FluentSQLite", "Vapor", "SwifQL", "SwifQLVapor"]),
        .target(name: "Run", dependencies: ["App"]),
        .testTarget(name: "AppTests", dependencies: ["App"])
    ]
)
```
then edit `boot.swift` to make it look like this
```bash
nano Sources/App/boot.swift
```
```swift
import Vapor
import SwifQL

/// Called after your application has initialized.
public func boot(_ app: Application) throws {
    // Your code here
        let query = SwifQL.select(1)
        print(query.prepare(.psql).plain)
}
```
then compile project
```bash
swift build
```
then if you're on macOS you'll see something like this
```bash
[53/53] Linking ./.build/x86_64-apple-macosx/debug/Run
```
so you could try to run it just by executing
```bash
./.build/x86_64-apple-macosx/debug/Run
```
if you're on Ubuntu then you'll see another path to `Run` so just execute it

Could you test and tell if it works or not?

P.S. I'm on `Vapor 3.1.1` and `macOS 10.14`

**Comment by MihaelIsaev** [comment]
@m-maillot if it works in clean project then you could try to do the following in your project
```bash
rm -rf .build && rm Package.resolved
swift package update
swift package generate-xcodeproj
```

**Comment by m-maillot** [comment]
Yes, it works sometimes. I think it's more an issue with SPM. Thanks!
