### ISSUE TITLE
Add Carthage support (check in scheme files)

### ISSUE THREAD

**Issue by davisford** [MihaelIsaev/SwifQL#3]
*** Skipped building SwifQL due to the error:
Dependency "SwifQL" has no shared framework schemes

If you believe this to be an error, please file an issue with the maintainers at https://github.com/MihaelIsaev/SwifQL/issues/new

**Comment by davisford** [comment]
See for example: https://github.com/Carthage/Carthage/issues/1075#issuecomment-177425825

**Comment by MihaelIsaev** [comment]
Hey @davisford 

Are you using Carthage for server-side Swift project or you'd like to use `SwifQL` in iOS/macOS app?

**Comment by davisford** [comment]
iOS

**Comment by MihaelIsaev** [comment]
That's interesting! I can't imagine as iOS project with MySQL/PostgreSQL onboard 🙂 I'd love to know more about the project if possible, cause if this lib is interesting for iOS, then I also add cocoapods support together with Carthage 🙂

**Comment by davisford** [comment]
I have kind of a unique situation.  I'm not having PostgreSQL in the client -- do have on the backend.  But we have our own query format we pass thru WebSockets.  I was looking to experiment with this lib to see if I can use the nice API and then take the intermediate format to generate what I want.  But I think it is probably overkill.  Thinking it may be simpler / more effective to just build our own QueryBuilder with builder pattern.

**Comment by MihaelIsaev** [comment]
Yeah, building SQL queries on the client sounds insecure 🙂 
I've just read how to implement Carthage support, and tbh it's kinda tricky, cause I should generate xcodeproj and share build schemes. So if you don't need it at the moment then I won't do it asap 🙂

**Comment by davisford** [comment]
FWIW -- we're not building SQL queries on the client.  We're building a custom query structure that gets passed through a websocket protocol.  SQL injection attacks are protected on the server.

**Comment by MihaelIsaev** [comment]
Yeah, thanks for clarifying, now I got the idea 🙂
