### ISSUE TITLE
Model Custom Table Name doesn't appear to work

### ISSUE THREAD

**Issue by bcousins** [MihaelIsaev/SwifQL#6]
Hey. 

So, I'm currently trying to move from Fluent to SwifQL using Vapor. Full disclosure, I'm relatively new to Swift in general; I've always found the quickest and easiest way to learn a new language is to stumble your way through. Which brings me here, because I don't fully understand what's happening here. 

From what I can ascertain of my issue: 

- I have a model (News) which has a custom database table name (n_articles) - this is placed into the Model as `static let entity = "n_articles"`, and Fluent is happy with that, it builds, it runs the query `SELECT * from 'n_articles' LIMIT 10 DESC` (or similar) happily.
- Reads the SwifQL docs, I need to use `News.table` to read from that model. 
- When building using SwifQL instead of Fluent, SwifQL attempts to run `SELECT News.* FROM News ORDER BY News.n_articleid DESC LIMIT ? [integer8(10)]` instead. Which, obviously won't work, since `News` isn't a table we have. 

Query looks like this:
`SwifQLSelectBuilder()
         .select(News.table.*)
         .from(News.table)
         .orderBy(.desc(\News.n_articleid))
         .limit(10)
         .build()
         .execute(on: req, as: .mysql)
         .all(decoding: News.self)`

I don't know if it's my model, or the query. But it's driving me mad.

**Comment by MihaelIsaev** [comment]
Hey @bcousins 
It looks like you haven't conformed `News` to `Tableable` protocol. When you do that SwifQL will start getting the right `n_articles` name for that table.
Please let me know if it works for you 🙂

**Comment by bcousins** [comment]
Sorry, I was hasty in closing this because just after I posted this, I found a way to do what I wanted in Fluent. Now I am interested in if I can get SwifQL working instead, since it's got a more MySQL-y syntax. 

Would you have an example of a model built using `Tableable`, rather than`Model`? There's not an awful lot of documentation.

**Comment by MihaelIsaev** [comment]
> There's not an awful lot of documentation.
Sorry for that, I'll try to find time to make it better asap.

Conforming you model to `Tableable ` is pretty easy, just go to your `News` model file and add
```swift
extension News: Tableable {}
```
cause since you use Vapor your model is already have `entity` variable which is needed to satisfy `Tableable` conformance.

> Would you have an example of a model built using Tableable, rather thanModel?
Sure, but since I'm using Postgres I can provide an example for it (sorry)
```swift
import Vapor
import FluentPostgreSQL
import SwifQL

final class EmailVerification: Content {
    public static var createdAtKey: TimestampKey? { return \.createdAt }
    
    var id: UUID?
    var userId: User.ID
    var code: String
    var createdAt: Date?
    
    init(id: UUID? = nil, userId: User.ID, code: String) {
        self.id = id
        self.userId = userId
        self.code = code
    }
}

extension EmailVerification: PostgreSQLUUIDModel {}
extension EmailVerification: Tableable {}
extension EmailVerification: Migration {
    static func prepare(on connection: PostgreSQLConnection) -> Future<Void> {
        return Database.create(self, on: connection) { builder in
            try addProperties(to: builder)
        }
    }
}
```

Any `Model` in your project which you'd like to use with `SwifQL` you should conform to `Tableable` 🙂

**Comment by bcousins** [comment]
> Conforming you model to Tableable is pretty easy

Seriously? That's it? That was easy! Then presumably I can use the same Leaf syntax within views to access components of this query?

Just verifying at this point, I have a successful build using SwifQL. 

One more question, is there a way for me to not have to install Vapor's Postgres support since I am not using it? I noticed it installed when I pulled SwifQL.

**Comment by MihaelIsaev** [comment]
> Then presumably I can use the same Leaf syntax within views to access components of this query?

I'm not sure that I understood you correctly, could you please rephrase.

>  is there a way for me to not have to install Vapor's Postgres support since I am not using it? I noticed it installed when I pulled SwifQL.

I have MySQL and PostgreSQL in dependencies only to provide [this extension](https://github.com/MihaelIsaev/SwifQL/blob/master/Sources/SwifQLVapor/SwifQLable%2BExecute.swift)

It looks like I could create two more packages in addition to `SwifQLVapor` to split MySQL and PostgreSQL. In this case e.g. to start using SwifQL + Vapor + MySQL developer should add `SwifQL`, `SwifQLVapor` and `SwifQLVaporMySQL` in target in `Package.swift`. Will it be convenient?

**Comment by bcousins** [comment]
> I'm not sure that I understood you correctly, could you please rephrase.

No, you understood fine. 

> It looks like I could create two more packages in addition to SwifQLVapor to split MySQL and PostgreSQL.

There's no need for you to do that; I'm not worried about it, I just noticed it when I did `swift package update`. If it needs it to provide something, I'm happy to leave it there.

**Comment by MihaelIsaev** [comment]
@bcousins thanks for this issue, if you don't mind I'll close it 🙂 
when you will have new questions please feel free to open new issues 🙂
