### ISSUE TITLE
Supporting Date in selects

### ISSUE THREAD

**Issue by Igor-Palaguta** [MihaelIsaev/SwifQL#9]
It  would be great if we can use Date in where clause

**Comment by MihaelIsaev** [comment]
@Igor-Palaguta could you check this commit https://github.com/MihaelIsaev/SwifQL/commit/321a0472b97e4678b1f08a4345d0bcd9750b5e28 cause it should work with both MySQL and PostgreSQL.

I've just checked it in my projects, here is an example
```swift
SwifQL.select(User.table.*).from(User.table).where(\User.createdAt >= Date())
```

**Comment by Igor-Palaguta** [comment]
Cool. Let me check

**Comment by Igor-Palaguta** [comment]
Thanks! Works like a charm
